### ISSUE TITLE
RGBA color format looks wrong if saved to another bmp.

### ISSUE THREAD

**Issue by fastcoding** [luapower/bmp#2]
I tried to load a bmp file (in RGBA color format) and save it to another bmp (even in the exactly same color format ), the new bmp file will have wrong color format.  If I change the Line#251 

> for ci, color in ipairs{'r', 'g', 'b', 'a'} do

to

> for ci, color in ipairs{'a', 'r', 'g', 'b'} do

then the new bmp looks fine. 

But if I feed the new bmp data to libjpeg, the jpeg component can not finish the compressing process on this bmp data, the finish handler will not run. Don't know if any internal bmp data is corrupted.

I got the same result on both Mac or Windows.

Is it a bug? 

attached a zip file containing my test script and a sample bmp file.

[Archive.zip](https://github.com/luapower/bmp/files/2612481/Archive.zip)

**Comment by capr** [comment]
Hi!

I don't think that change is right. If you run the bmp demo file you will notice that it saves the bitmaps it loads back in media/bmp and you can check the results there (eg. compare `rgb16-565pal-saved.bmp` with `rgb16-565pal.bmp`).

As for jpeg, try to run libjpeg_test.lua which tests both loading and saving, and if that works, try to compare the code there with your own code.

Hope this helps.

**Comment by fastcoding** [comment]
> I don't think that change is right. If you run the bmp demo file you will notice that it saves the bitmaps it loads back in media/bmp and you can check the results there (eg. compare `rgb16-565pal-saved.bmp` with `rgb16-565pal.bmp`).

thanks for your quick reply.

I just copied my test bmp file to luapower-all-master/media/bmp/good and used the bmp_demo.lua to test this on Windows 7.  I still got the same result - the saved bmp's color is not correct as shown below.

<img width="419" alt="screen shot 2018-11-25 at 8 27 26 pm" src="https://user-images.githubusercontent.com/8646035/48979241-affac800-f0f2-11e8-8da7-facd37e427b2.png">

**Comment by capr** [comment]
fixed the color channel bug in 25733a99f077bde8215d7d7939c96ea2371659bc
